version: "3"

services:
  db:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
  
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RAILS_ENV=${RAILS_ENV}
        - RACK_ENV=${RACK_ENV}
        - RAILS_SERVE_STATIC_FILES=${RAILS_SERVE_STATIC_FILES}
        - SECRET_KEY_BASE=${SECRET_KEY_BASE}
        - DATABASE_HOST=${DATABASE_HOST}
        - DATABASE_NAME=${DATABASE_NAME}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - DATABASE_PORT=${DATABASE_PORT}
        - DATABASE_USERNAME=${DATABASE_USERNAME}
        - API_ADDRESS=${API_ADDRESS}
        - CONSUMER_KEY=${CONSUMER_KEY}
        - CONSUMER_SECRET=${CONSUMER_SECRET}
        - CODE=${CODE}
        - LOGIN_URL_SNK=${LOGIN_URL_SNK}
        - VIEW_URL_SNK=${VIEW_URL_SNK}
        - URL_API_SNK=${URL_API_SNK}
        - URL_API_SNK_POST=${URL_API_SNK_POST}
        - URL_SNK_ORDER_POST=${URL_SNK_ORDER_POST}
        - NOMUSU=${NOMUSU}
        - INTERNO=${INTERNO}
        - CODTIPOPER=${CODTIPOPER}
        - CODTIPVENDA=${CODTIPVENDA}
        - CODVEND=${CODVEND}
        - CODEMP=${CODEMP}
        - TIPMOV=${TIPMOV}
        - CODNAT=${CODNAT}
        - CODPARCTRANSP=${CODPARCTRANSP}
        - CODLOCALORIG=${CODLOCALORIG}
        - CODCENCUS=${CODCENCUS}
    ports:
      - 3000:3000
    depends_on: 
      - db
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems

  # app-products-task:
  #   command: ./cron_products_task.sh
  #   env_file:
  #     - .env
  #   depends_on:
  #     - app
  #   stdin_open: true
  #   tty: true

  # app-stock-task:
  #   command: ./cron_stock_task.sh
  #   env_file:
  #     - .env
  #   depends_on:
  #     - app
  #   stdin_open: true
  #   tty: true

  # app-orders-task:
  #   command: ./cron_stock_task.sh
  #   env_file:
  #     - .env
  #   depends_on:
  #     - app
  #   stdin_open: true
  #   tty: true

volumes:
  gem_cache:
  db_data: