default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  database: api_tray_sankhya_development
  port: <%= ENV["DATABASE_PORT"] %>

test:
  <<: *default
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  database: api_tray_sankhya_test
  port: <%= ENV["DATABASE_PORT"] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
